image: node:14

before_script:
  - npm install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

test:
  script:
    - npm run ci
  coverage: /All files\s+\|\s+([\d.]+)/
